#!/usr/bin/env sh
printf "\e[33;1m%s\e[0m\n" 'Running tests'
npm run test

if [ $? -ne 0 ]; then
  printf "\e[31;1m%s\e[0m\n" 'Running tests error'
exit 1 fi

printf "\e[33;1m%s\e[0m\n" 'Finished running tests'