name: Tests

on:
  pull_request_target:
    types: [opened, synchronize, edited]
    branches:
      - 'main'

jobs:
  tests:
    runs-on: ubuntu-latest

    name: Run Tests
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup node
        uses: actions/setup-node@v3
        with:
          node-version: 14

      - name: Install dependencies
        run: npm i

      - name: Run tests
        run: npm run test
